name: Release Artifacts

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: macos-latest
    env:
      CGO_ENABLED: 0

    steps:
    - name: Check out source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.21.1'

    # Linux
    - name: Build linux x86-64 artifact
      env:
        GOOS: linux
        GOARCH: amd64
      run: go build -trimpath -o bin/large-json-splitter_${GOOS}_${GOARCH}

    - name: Build linux arm64 artifact
      env:
        GOOS: linux
        GOARCH: arm64
      run: go build -trimpath -o bin/large-json-splitter_${GOOS}_${GOARCH}

    # macOS
    - name: Build macOS x86-64 artifact
      env:
        GOOS: darwin
        GOARCH: amd64
      run: go build -trimpath -o bin/large-json-splitter_${GOOS}_${GOARCH}

    - name: Build macOS arm64 artifact
      env:
        GOOS: darwin
        GOARCH: arm64
      run: go build -trimpath -o bin/large-json-splitter_${GOOS}_${GOARCH}

    # Windows
    - name: Build Windows x86-64 artifact
      env:
        GOOS: windows
        GOARCH: amd64
      run: go build -trimpath -o bin/large-json-splitter_${GOOS}_${GOARCH}.exe

    - name: Generate change log for release
      run: curl -sSf 'https://raw.githubusercontent.com/KENKEN0803/changelog.sh/main/changelog.sh' | zsh -s -- '' '' --md > changelog.md

    - name: Release artifacts
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: bin/*
        body_path: changelog.md
